### ISSUE TITLE
Close the dropdown menu by clicking on the option

### ISSUE THREAD

**Issue by kryloff** [CodyHouse/cd-dropdown-changelog#1]
Hi, I quickly added part of the js code to make dropdown part close by clicking on the mega-site-navigation and language-picker options, but after spending a few hours I still couldn't find a way to modify the code so that the dropdown menu closes by clicking on the option. Can you help me do this?

**Comment by claudia-romano** [comment]
Hi, the Dropdown object has a ```hideDropdown``` method that you can use. 
If you are modifying the code of the component and you added an event listener for the click, you could do something like:
```
var self = this;
this.dropdown.addEventListener('click', function(){
  self.hideDropdown();
});
```
That should do it. Cheers.

**Comment by kryloff** [comment]
> Hi, the Dropdown object has a `hideDropdown` method that you can use.
> If you are modifying the code of the component and you added an event listener for the click, you could do something like:
> 
> ```
> var self = this;
> this.dropdown.addEventListener('click', function(){
>   self.hideDropdown();
> });
> ```
> 
> That should do it. Cheers.

Unfortunately, this doesn't work. You can easily check this out

**Comment by claudia-romano** [comment]
Hi there, the component comes with the `Dropdown` object you can use to initialise your element (rather than using the default `.js-dropdown` class). 
If you use the `Dropdown` object and store it after initializations, you can use all its public methods (including `hideDropdown`).
