### ISSUE TITLE
remove ".js-dropdown__xxx" classes from js code

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-dropdown-changelog#2]
All ".js-dropdown__xxx" classes (except the root one: ".js-dropdown") can be removed from HTML/JS codes, they are redundant, and can be replaced by the ones without the "js-" prefix.

Clearer codes, less unused classes.

This may apply to other components as well?

**Comment by claudia-romano** [comment]
Hi there,
the js classes are used to separate behaviour from style. 
Let's say you want to create a variation of the dropdown component: you'll be using different css classes (e.g., `.dropdown--v2`, `.dropdown--v2__trigger`) but you won't need to recreate the js code (you'll still have the same js classes, `.js-dropdown`, `.js-dropdown__trigger`).

**Comment by dean-shanghai** [comment]
fair enough, 

one of the reasons i'm asking about this is the two different styles below:

1.https://codyhouse.co/ds/components/app/dropdown, the dropdown component js code are using .js-xxx style classes;

2.while in the Mercurio template, in the _2_dropdown.js file, you are using classes without "js-" prefixes.

**Comment by claudia-romano** [comment]
Hi there,
we do regularly update our components. This is one of the changes we recently made to the dropdown to improve it. You can see the list of all the changes made to the component on the changelog page:
https://github.com/CodyHouse/cd-dropdown-changelog/commits/master
