### ISSUE TITLE
It doens't work on iOS

### ISSUE THREAD

**Issue by retroriff** [CodyHouse/cd-dropdown-changelog#3]
Hello, the dropdown is not working on iOS Safari because the pointer media doesn't allow it to open. Has this dropdown been designed to work only with with a mouse device?

```
@media (pointer: fine) {
    .dropdown__menu--is-visible {  
      opacity: 1;
      visibility: visible;
      transition: opacity .2s;
    }
 }

**Comment by claudia-romano** [comment]
Hi there,
yes the dropdown component was designed to reveal the list of related links when using the mouse. On touch devices, the click on the dropdown link will directly redirect the user to the selected page.

If you want to modify this behaviour, you can either:
1 - remove the  .dropdown__menu--is-visible class from the pointer media;
2 - use a different component, like the Menu or Popover component:
https://codyhouse.co/ds/components/app/menu
https://codyhouse.co/ds/components/app/popover

Cheers

**Comment by retroriff** [comment]
Thank you for the explanation
