### ISSUE TITLE
Logic improvement in Dropdown.prototype.initElementEvents

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-dropdown-changelog#4]
File#: _2_dropdown
method: Dropdown.prototype.initElementEvents = function(element, bool) { **...logic here...** }

**Question**: what's the use the bool parameter? it's never used.
**Suggestion**: add `self.placeElement();` before `self.showDropdown();`, to make sure the dropdown menu is correctly placed after window resizing.

**Comment by claudia-romano** [comment]
Hi Dean,
- The bool params is used to pass two different props of the Dropdown object based on the action that triggered the function call (this.triggerFocus/this.dropdownFocus) and change them accordingly;

- Do you have an example where it would be useful to call the placeElement method before the showDropdown one?

Thanks!

**Comment by dean-shanghai** [comment]
1. about the bool param: OK
2. about the placeElement method, check the difference between the following gifs:
a). **without** placeElement:
![no](https://user-images.githubusercontent.com/6344066/93294157-5e1db780-f81c-11ea-8572-056f2ea10182.gif)
b). **with** placeElement:
![with-placeElement](https://user-images.githubusercontent.com/6344066/93294066-231b8400-f81c-11ea-9502-b40540139207.gif)

**Comment by claudia-romano** [comment]
Hi Dean,
thanks for providing this additional info. We have pushed an updated version of the component with an improved dropdown placement.

You can get the updated JS code here:
https://codyhouse.co/ds/components/app/dropdown

Cheers!
