### ISSUE TITLE
Dropdown not working on mobile

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-dropdown-changelog#5]
Hy, the Dropdown is not working on mobile.

If you make any changes, may i suggest you to use the Visibility class for the icon in the html markup?

**Comment by claudia-romano** [comment]
Hi Dario, this is by choice. You can find more details in the component Info page:
https://codyhouse.co/ds/components/info/dropdown#mobile-devices

Feel free to reopen the issue if you need further assistance. Cheers!

**Comment by dariopetraroia** [comment]
Oh sorry thank you
